name: Daily Spotify Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"   # Her gün sabah 07:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger load_podcast
        run: |
          curl -s -X GET "$RENDER_BASE_URL/load_podcast"
        env:
          RENDER_BASE_URL: ${{ secrets.RENDER_BASE_URL }}

      - name: Trigger sync_unplayed
        run: |
          curl -s -X GET "$RENDER_BASE_URL/sync_unplayed"
        env:
          RENDER_BASE_URL: ${{ secrets.RENDER_BASE_URL }}

      - name: Trigger sync_playlist
        run: |
          curl -s -X GET "$RENDER_BASE_URL/sync_playlist"
        env:
          RENDER_BASE_URL: ${{ secrets.RENDER_BASE_URL }}
