name: Daily Spotify Sync

on:
  workflow_dispatch:       # Manuel tetikleme
  schedule:
    - cron: '0 7 * * *'    # Her gün sabah 07:00 UTC (Kaliforniya için gece yarısı gibi)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger load_podcast on Render
        env:
          BASE: ${{ secrets.RENDER_BASE_URL }}
        run: |
          echo "Calling $BASE/load_podcast"
          curl --fail --silent --show-error --max-time 120 "$BASE/load_podcast" -o /tmp/load_podcast_resp.json
          echo "load_podcast returned:"
          cat /tmp/load_podcast_resp.json

      - name: Trigger sync (update queue)
        env:
          BASE: ${{ secrets.RENDER_BASE_URL }}
        run: |
          echo "Calling $BASE/sync"
          curl --fail --silent --show-error --max-time 120 "$BASE/sync" -o /tmp/sync_resp.html
          echo "sync returned:"
          head -n 20 /tmp/sync_resp.html
